apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ampara
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - postgres-statefulset.yaml
secretGenerator:
  - name: adocao-secret
    envs: [secret.env]
generatorOptions:
  disableNameSuffixHash: true
